import {randomUUID,randomInt} from 'node:crypto';
const rooms=globalThis.__guepardRooms??=new Map();
const defaults={textType:'story',length:50,punctuation:true,accents:true,numbers:false,blockErrors:false,bots:0,difficulty:'medium',timeLimit:120};
function fail(message,status=400){throw Object.assign(new Error(message),{status})}
function cleanName(name){if(typeof name!=='string'||!name.trim()||name.trim().length>24)fail('Choisissez un pseudo de 1 à 24 caractères.');return name.trim()}
function find(code){const room=rooms.get(String(code).toUpperCase());if(!room||Date.now()-room.createdAt>86400000)fail('Ce salon est introuvable ou a expiré.',404);return room}
function member(room,token){const p=room.people.find(p=>p.token===token);if(!p)fail('Vous ne faites plus partie de ce salon.',403);return p}
function settings(input){const next={...defaults,...input};if(!['story','words'].includes(next.textType)||![25,50,100,200].includes(next.length)||![0,60,120,300].includes(next.timeLimit)||![0,1,2,3,4,5].includes(next.bots)||!['easy','medium','expert'].includes(next.difficulty))fail('Paramètres invalides.');for(const k of ['punctuation','accents','numbers','blockErrors'])if(typeof next[k]!=='boolean')fail('Paramètres invalides.');return Object.fromEntries(Object.keys(defaults).map(k=>[k,next[k]]))}
function view(room,p){return {...room,people:room.people.map(({token,...person})=>person),me:p.id,isHost:p.id===room.hostId}}
export function textFor(s,language){const fr=language!=='EN';const prose=fr?'Le guépard traverse la forêt près de la rivière. Les oiseaux colorés chantent dans les branches. Un éléphant découvre une clairière ensoleillée et partage des mangues avec ses amis. Chaque matin la jungle s’éveille doucement sous un ciel doré.':'The cheetah crosses the forest near the river. Colourful birds sing in the branches. A little elephant finds a sunny clearing and shares mangoes with friends. Every morning the jungle slowly wakes under a golden sky.';const words=fr?'jungle forêt rivière guépard éléphant mangue soleil feuille branche clairière aventure perroquet vitesse amitié lumière':'jungle forest river cheetah elephant mango sun leaf branch clearing adventure parrot speed friendship light';let result=Array.from({length:s.length},(_,i)=>(s.textType==='story'?prose:words).split(' ')[i%(s.textType==='story'?prose:words).split(' ').length]);if(s.numbers)result=result.map((w,i)=>i%10===9?String((i+1)*3):w);let text=result.join(' ');if(!s.punctuation)text=text.replace(/[.,!?;:’']/g,'');if(!s.accents)text=text.normalize('NFD').replace(/[\u0300-\u036f]/g,'');return text}
export function listLobbies(){return [...rooms.values()].filter(r=>r.visibility==='public'&&r.phase==='waiting'&&Date.now()-r.createdAt<86400000).map(r=>({code:r.code,name:r.name,players:r.people.length+r.settings.bots,language:r.language}))}
export function createLobby(input){for(const [key,r]of rooms)if(Date.now()-r.createdAt>86400000)rooms.delete(key);if(rooms.size>=200)fail('Trop de salons ouverts. Réessayez plus tard.',429);let code;do{code=Array.from({length:6},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[randomInt(32)]).join('')}while(rooms.has(code));const host={id:randomUUID(),token:randomUUID(),name:cleanName(input.nickname),role:'player',avatar:['🐆','🦜','🐊','🦁'].includes(input.avatar)?input.avatar:'🐆'};const visibility=['public','semi','private'].includes(input.visibility)?input.visibility:'semi';const room={code,name:String(input.name||'Course entre amis').slice(0,60),language:input.language==='EN'?'EN':'FR',visibility,hostId:host.id,people:[host],settings:{...defaults},phase:'waiting',createdAt:Date.now(),revision:0};rooms.set(code,room);return {room:view(room,host),token:host.token}}
export function getLobby(code,token){const room=find(code);return view(room,member(room,token))}
export function changeLobby(code,token,input){const room=find(code);if(input.action==='join'){if(room.phase!=='waiting')fail('La course a déjà commencé.');if(room.people.length+room.settings.bots>=16)fail('Le salon est complet.');const p={id:randomUUID(),token:randomUUID(),name:cleanName(input.nickname),role:input.role==='spectator'?'spectator':'player',avatar:['🐆','🦜','🐊','🦁'].includes(input.avatar)?input.avatar:'🐆'};room.people.push(p);room.revision++;return {room:view(room,p),token:p.token}}
 const p=member(room,token);if(input.action==='leave'){if(p.id===room.hostId){rooms.delete(room.code);return {closed:true}}room.people=room.people.filter(x=>x.id!==p.id);room.revision++;return {left:true}}
 if(input.action==='role'){if(room.phase!=='waiting')fail('La course a déjà commencé.');if(!['player','spectator'].includes(input.role))fail('Rôle invalide.');p.role=input.role}
 else{if(p.id!==room.hostId)fail('Seul l’hôte peut modifier le salon.',403);if(input.action==='reset'){room.phase='waiting';delete room.text;delete room.startedAt}
 else{if(room.phase!=='waiting')fail('La course a déjà commencé.');if(input.action==='settings'){const next=settings({...room.settings,...input.settings});if(room.people.length+next.bots>16)fail('Maximum 16 participants et bots.');room.settings=next}
 else if(input.action==='kick'){if(input.id===room.hostId)fail('Vous ne pouvez pas retirer l’hôte.');room.people=room.people.filter(x=>x.id!==input.id)}
 else if(input.action==='start'){if(!room.people.some(x=>x.role==='player'))fail('Il faut au moins un joueur.');room.text=textFor(room.settings,room.language);room.startedAt=Date.now()+3000;room.phase='running'}else fail('Action inconnue.')}}room.revision++;return {room:view(room,p)}}
