import {randomUUID,randomInt} from 'node:crypto';
import {isAnimal} from '../lib/animals';
import {defaultSettings, type Room,type Person,type RoomView,type Settings,type Difficulty} from '../lib/room-types';
export class RoomError extends Error{constructor(message:string,public status=400){super(message)}}
function requireValue(condition:unknown,message:string,status=400):asserts condition{if(!condition)throw new RoomError(message,status)}
export function name(value:unknown){requireValue(typeof value==='string'&&value.trim().length>0&&value.trim().length<=40,'Le pseudo doit contenir de 1 à 40 caractères.');return value.trim()}
function person(body:any):Person{return {id:randomUUID(),token:randomUUID(),name:name(body.nickname),animal:body.kind==='demo'&&isAnimal(body.avatar)?body.avatar:'cheetah',kind:body.kind==='demo'?'demo':'guest',role:'player',late:false,seen:Date.now(),progress:0,errors:0,typed:0,abandoned:false}}
export function createRoom(body:any):{room:Room;person:Person}{requireValue(isAnimal(body.animal),'Choisissez un animal pour la course.');requireValue(typeof body.name==='string'&&body.name.trim().length>0&&body.name.length<=80,'Donnez un nom au salon (80 caractères maximum).');const host=person(body);const room:Room={id:randomUUID(),name:body.name.trim(),animal:body.animal,code:Array.from({length:8},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[randomInt(32)]).join(''),hostId:host.id,people:[host],settings:validateSettings({...defaultSettings,visibility:body.visibility||'semi',language:body.language||'FR'}),phase:'waiting',createdAt:Date.now(),revision:1,invites:[]};return {room,person:host}}
export function authenticate(room:Room,token:string){const p=room.people.find(p=>p.token===token&&p.kind!=='bot');requireValue(p,'Vous ne faites plus partie de ce salon.',403);return p}
export function validateSettings(s:Settings):Settings{requireValue(['public','semi','private'].includes(s.visibility)&&['FR','EN'].includes(s.language)&&['story','words','custom'].includes(s.textType)&&['jungle','adventure','science'].includes(s.bank),'Paramètres invalides.');for(const [k,min,max]of [['length',20,1000],['timeLimit',0,3600],['targetWpm',0,400],['inactiveAfter',15,600]] as const)requireValue(Number.isInteger(s[k])&&s[k]>=min&&s[k]<=max,'Valeur de paramètre hors limites.');for(const k of ['blockErrors','punctuation','accents','numbers','specials'] as const)requireValue(typeof s[k]==='boolean','Option invalide.');requireValue(typeof s.blacklist==='string'&&s.blacklist.length<=100&&typeof s.customText==='string'&&s.customText.length<=15000,'Texte trop long.');return Object.fromEntries(Object.keys(defaultSettings).map(k=>[k,s[k as keyof Settings]])) as unknown as Settings}
export function generateText(s:Settings):string{
 const fr=s.language==='FR';const banks={jungle:fr?'forêt rivière guépard éléphant mangue soleil feuille branche clairière aventure perroquet lumière':'forest river cheetah elephant mango sunshine leaf branch clearing adventure parrot light',adventure:fr?'voyage boussole trésor montagne chemin bateau étoile carte découverte cascade':'journey compass treasure mountain path boat star map discovery waterfall',science:fr?'planète atome énergie lumière cellule espace matière orbite océan expérience':'planet atom energy light cell space matter orbit ocean experiment'};
 const sentences=fr?['Le guépard suit la rivière sous les grandes feuilles.','Un perroquet coloré se pose près de la cascade.','Dans la clairière les amis partagent des mangues mûres.','Le soleil éclaire les branches de la forêt.']:['The cheetah follows the river under the giant leaves.','A colourful parrot lands near the waterfall.','Friends share sweet mangoes in the jungle clearing.','The sun lights up the branches of the forest.'];
 let text=s.customText.trim();if(s.textType!=='custom'){const pool=s.textType==='words'?banks[s.bank].split(' '):Array.from({length:Math.ceil(s.length/5)+1},()=>sentences[randomInt(sentences.length)]).join(' ').split(' ');text=Array.from({length:s.length},(_,i)=>s.textType==='words'?pool[randomInt(pool.length)]:pool[i%pool.length]).join(' ');if(s.numbers)text=text.split(' ').map((w,i)=>i%11===8?String(randomInt(100)):w).join(' ');if(s.specials)text=text.split(' ').map((w,i)=>i%13===7?['@','#','+'][i%3]:w).join(' ');}
 if(!s.accents)text=text.normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(!s.punctuation)text=text.replace(/[.,;:!?’'"…()\-]/g,'');if(!s.numbers)text=text.replace(/\d/g,'');if(!s.specials)text=text.replace(/[@#$%&*+=<>_~^|/\\{}\[\]]/g,'');text=[...text].filter(c=>!s.blacklist.includes(c)).join('').replace(/\s+/g,' ').trim();requireValue(text.length>=10,'Ces réglages ne laissent pas assez de texte.');return text;
}
export function tick(room:Room){if(room.phase!=='running'||!room.startedAt||Date.now()<room.startedAt)return;if(Date.now()-(room.lastTick||0)<500)return;room.lastTick=Date.now();const elapsed=(Date.now()-room.startedAt)/1000;const size=room.text?.length||1;let changed=false;for(const p of room.people){if(p.role!=='player'||p.abandoned||p.finishedAt)continue;if(p.kind==='bot'){const speed={beginner:25,medium:50,expert:85,impossible:140}[p.difficulty||'medium'];const wave=1+Math.sin(elapsed/3+p.id.length)*.14;const next=Math.min(size,Math.floor(elapsed*speed*5/60*wave));p.progress=Math.max(p.progress,next);p.typed=p.progress+Math.floor(p.progress*.03);p.errors=p.typed-p.progress;if(p.progress===size)p.finishedAt=Date.now();changed=true}else if(Date.now()-(p.lastInput||room.startedAt)>room.settings.inactiveAfter*1000){p.abandoned=true;changed=true}}
 const players=room.people.filter(p=>p.role==='player');if((room.settings.timeLimit>0&&elapsed>=room.settings.timeLimit)||players.every(p=>p.finishedAt||p.abandoned)){room.phase='finished';changed=true}if(changed)room.revision++;
}
export function snapshot(room:Room,p:Person):RoomView{const {invites,...safe}=room;return {...safe,people:room.people.map(({token,input,...other})=>({...other,...(other.id===p.id?{input}:{} )})),me:p.id,isHost:p.id===room.hostId,players:room.people.filter(p=>p.role==='player'&&!p.abandoned).length,serverNow:Date.now()}}
export function joinRoom(room:Room,body:any):Person{if(room.settings.visibility==='semi')requireValue(body.code===room.code,'Le code du salon est incorrect.',403);if(room.settings.visibility==='private'){const invite=room.invites.find(i=>i.token===body.invite&&!i.used&&i.expires>Date.now());requireValue(invite,'Invitation expirée ou déjà utilisée.',403);invite.used=true}const p=person(body);if(room.phase!=='waiting'){p.role='spectator';p.late=true}room.people.push(p);room.revision++;return p}
export function act(room:Room,p:Person,body:any):any{
 p.seen=Date.now();if(body.action==='heartbeat')return {};
 if(body.action==='progress'){requireValue(room.phase==='running'&&room.startedAt&&Date.now()>=room.startedAt&&p.role==='player'&&!p.abandoned,'Vous ne pouvez pas taper maintenant.');const input=String(body.value||'').slice(0,room.text!.length);if(room.settings.blockErrors)requireValue(room.text!.startsWith(input),'Corrigez les erreurs avant de continuer.');p.lastInput=Date.now();p.input=input;p.progress=[...input].filter((c,i)=>c===room.text![i]).length;p.typed=Math.max(input.length,Number(body.typed)||input.length);p.errors=Math.max(0,p.typed-p.progress);if(input===room.text)p.finishedAt=Date.now();room.revision++;tick(room);return {}}
 if(body.action==='abandon'){p.abandoned=true;room.revision++;tick(room);return {}}
 requireValue(p.id===room.hostId,'Seul l’hôte peut effectuer cette action.',403);
 if(body.action==='invite'){requireValue(room.settings.visibility==='private','Le salon n’est pas privé.');const invitation={token:randomUUID(),expires:Date.now()+30*60*1000,used:false};room.invites=room.invites.filter(i=>!i.used&&i.expires>Date.now());room.invites.push(invitation);return {invitation}}
 if(body.action==='kick'){requireValue(body.personId!==p.id,'Vous ne pouvez pas retirer l’hôte.');room.people=room.people.filter(x=>x.id!==body.personId);room.revision++;tick(room);return {}}
 if(body.action==='reset'){requireValue(room.phase!=='waiting','Le salon est déjà en attente.');room.phase='waiting';delete room.startedAt;delete room.text;room.people.forEach(x=>{if(x.late){x.role='player';x.late=false}delete x.input;delete x.lastInput;x.progress=0;x.errors=0;x.typed=0;x.abandoned=false;delete x.finishedAt});room.revision++;return {}}
 requireValue(room.phase==='waiting','Les réglages sont verrouillés pendant la course.');
 if(body.action==='settings'){room.settings=validateSettings({...room.settings,...body.settings});if(body.settings?.visibility)room.invites=[]}
 else if(body.action==='role'){requireValue(['player','spectator'].includes(body.role),'Rôle invalide.');const target=room.people.find(x=>x.id===body.personId);requireValue(target,'Participant introuvable.');target.role=body.role;target.late=false}
 else if(body.action==='bot'){const level:Difficulty=body.difficulty||'medium';requireValue(['beginner','medium','expert','impossible'].includes(level),'Niveau invalide.');room.people.push({...person({nickname:'Bot '+(room.people.filter(x=>x.kind==='bot').length+1)}),token:undefined,animal:room.animal,kind:'bot',difficulty:level})}
 else if(body.action==='difficulty'){const target=room.people.find(x=>x.id===body.personId&&x.kind==='bot');requireValue(target&&['beginner','medium','expert','impossible'].includes(body.difficulty),'Bot ou niveau invalide.');target.difficulty=body.difficulty}
 else if(body.action==='start'){requireValue(room.people.filter(x=>x.role==='player').length>=2,'Il faut au moins deux joueurs pour démarrer.');room.text=generateText(room.settings);room.startedAt=Date.now()+4000;room.phase='running';room.people.forEach(x=>{x.seen=Date.now();x.lastInput=room.startedAt})}
 else throw new RoomError('Action inconnue.');room.revision++;return {};
}
