import {test,expect} from '@playwright/test';
test('public browse lists only real rooms and quick play joins an available one',async({page,browser})=>{
 const before=(await (await page.request.get('/api/rooms')).json()).rooms;await page.goto('/races');await expect(page.locator('.expedition-card')).toHaveCount(before.length);
 const hostContext=await browser.newContext(),host=await hostContext.newPage();await host.goto('/private');await host.getByLabel('Nom du salon').fill('La course du toucan');await host.getByRole('radio',{name:/Perroquet/}).check();await host.getByLabel('Visibilité').selectOption('public');await host.getByRole('button',{name:/Créer le salon/}).click();await expect(host).toHaveURL(/\/lobby\//);const roomId=host.url().split('/').pop()!;
 try{const guest=await browser.newContext(),guestPage=await guest.newPage();await guestPage.goto(host.url());await guestPage.getByLabel('Ton pseudo').fill('Un ami');await guestPage.getByRole('button',{name:/Entrer dans le salon/}).click();await expect(guestPage.getByText('En attente du départ par l’hôte',{exact:true})).toBeVisible();await page.reload();await expect(page.locator('.expedition-card')).toHaveCount(before.length+1);await expect(page.getByRole('heading',{name:'La course du toucan'})).toBeVisible();await expect(page.getByRole('link',{name:/Rejoindre — La course du toucan/})).toBeVisible();await page.goto('/play');await expect(page).toHaveURL(new RegExp('/lobby/'+roomId));await expect(page.getByText('En attente du départ par l’hôte',{exact:true})).toBeVisible();await guest.close()}finally{const token=await host.evaluate(id=>sessionStorage.getItem('guepard-room-'+id),roomId);await host.request.post('/api/rooms/'+roomId,{headers:{Authorization:'Bearer '+token},data:{action:'leave'}});await hostContext.close()}
});
test('animal landscape, shared host settings, start, late spectator and tablet layout',async({page,browser})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/private');await page.getByLabel('Nom du salon').fill('La clairière des amis');await page.getByRole('radio',{name:/Perroquet/}).check();await page.getByLabel('Visibilité').selectOption('public');await page.getByRole('button',{name:/Créer le salon/}).click();await expect(page).toHaveURL(/\/lobby\//);const url=page.url(),id=url.split('/').pop()!;
 await expect(page.getByText('Vous êtes l’hôte',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Lancer la course'})).toBeDisabled();
 const visitor=await browser.newContext(),guest=await visitor.newPage();await guest.goto(url);await guest.getByLabel('Ton pseudo').fill('Sam');await guest.getByRole('button',{name:/Entrer dans le salon/}).click();await expect(guest.getByText('En attente du départ par l’hôte',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Lancer la course'})).toBeEnabled();await expect(guest.getByLabel('Visibilité')).toBeDisabled();
 await page.getByLabel('Longueur en mots').fill('200');await page.getByLabel('Longueur en mots').press('Tab');await expect(guest.getByLabel('Longueur en mots')).toHaveValue('200');
 await page.getByRole('button',{name:'Ajouter un bot',exact:true}).click();await expect(guest.getByLabel('Difficulté de Bot 1')).toBeVisible();
 await page.screenshot({path:'/tmp/guepard-lobby-desktop.png',fullPage:true});await page.setViewportSize({width:820,height:1180});await expect(page.locator('body')).toHaveJSProperty('scrollWidth',820);await page.screenshot({path:'/tmp/guepard-lobby-tablet.png',fullPage:true});await page.setViewportSize({width:390,height:844});await expect(page.locator('body')).toHaveJSProperty('scrollWidth',390);await page.screenshot({path:'/tmp/guepard-lobby-mobile.png',fullPage:true});await page.getByRole('button',{name:'Changer le thème'}).click();await page.screenshot({path:'/tmp/guepard-lobby-night.png',fullPage:true});
 await page.getByRole('button',{name:'Lancer la course'}).click();await expect(guest.getByLabel('Texte de la course')).toBeVisible();const lateContext=await browser.newContext(),late=await lateContext.newPage();await late.goto(url);await late.getByLabel('Ton pseudo').fill('Retardataire');await late.getByRole('button',{name:/Entrer dans le salon/}).click();await expect(late.getByText(/Mode spectateur/)).toBeVisible();await page.getByRole('button',{name:'Retour au salon',exact:true}).click();await expect(late.getByText('En attente du départ par l’hôte',{exact:true})).toBeVisible();
 const token=await page.evaluate(id=>sessionStorage.getItem('guepard-room-'+id),id);await page.request.post('/api/rooms/'+id,{headers:{Authorization:'Bearer '+token},data:{action:'leave'}});await expect(guest.getByText('Le salon n’est plus accessible.')).toBeVisible();expect(errors).toEqual([]);await visitor.close();await lateContext.close();
});
test('private invitations are consumed once and a class of 32 can share a room',async({request})=>{
 const created=await request.post('/api/rooms',{data:{name:'Classe de test',nickname:'Hôte',animal:'crocodile',visibility:'private'}});expect(created.ok()).toBeTruthy();const {room,token}=await created.json();const headers={Authorization:'Bearer '+token};
 try{const invitations=await Promise.all(Array.from({length:31},()=>request.post('/api/rooms/'+room.id,{headers,data:{action:'invite'}})));for(let i=0;i<invitations.length;i++){const {invitation}=await invitations[i].json();const join=await request.post('/api/rooms/'+room.id,{data:{action:'join',nickname:'Élève '+i,invite:invitation.token}});expect(join.ok()).toBeTruthy();const replay=await request.post('/api/rooms/'+room.id,{data:{action:'join',nickname:'Copie',invite:invitation.token}});expect(replay.status()).toBe(403)}const snapshot=await request.get('/api/rooms/'+room.id,{headers});expect((await snapshot.json()).room.people).toHaveLength(32);const listing=await request.get('/api/rooms');expect((await listing.json()).rooms.some((r:any)=>r.id===room.id)).toBe(false)}finally{await request.post('/api/rooms/'+room.id,{headers,data:{action:'leave'}})}
});
