import React from 'react';
import {vi,test,expect} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {SiteProvider} from '../src/components/SiteContext';
import Site from '../src/components/Site';
import {raceService} from '../src/data';
const navigation=vi.hoisted(()=>({path:'/',push:vi.fn(),replace:vi.fn()}));
vi.mock('next/navigation',()=>({usePathname:()=>navigation.path,useRouter:()=>({push:navigation.push,replace:navigation.replace})}));
vi.mock('next/link',()=>({default:({children,href,...props})=><a href={href} {...props}>{children}</a>}));
function mount(path='/'){navigation.path=path;return render(<SiteProvider><Site/></SiteProvider>)}
test('home has one scene, three real board links and preserved art',()=>{const {container}=mount();expect(container.querySelectorAll('main section')).toHaveLength(1);expect([...container.querySelector('#app').children].map(el=>el.tagName)).toEqual(['HEADER','MAIN','FOOTER']);expect(screen.getByRole('link',{name:/Créer une course privée/}).getAttribute('href')).toBe('/private');expect(screen.getByRole('link',{name:/Parcourir les courses$/}).getAttribute('href')).toBe('/races');expect(container.querySelector('.sleeping-cheetah')).not.toBeNull();expect(container.querySelector('header img').getAttribute('src')).toBe('/assets/guepard-logo.png')});
test('FR/EN, night mode, demo login, settings and logout',async()=>{mount();fireEvent.click(screen.getByRole('button',{name:'Choisir la langue'}));expect(screen.getByRole('link',{name:/Create a private race/})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Change theme'}));await waitFor(()=>expect(document.documentElement.dataset.theme).toBe('dark'));fireEvent.click(screen.getByRole('button',{name:'Log in'}));expect(screen.getByText(/Authentication is not available/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:/Explore the demo account/}));expect(screen.getByText('Demo account')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Settings',hidden:true}));fireEvent.change(screen.getByLabelText('Your nickname'),{target:{value:'Jungle'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));expect(screen.getByText('Jungle')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Log out',hidden:true}));expect(screen.getByRole('button',{name:'Log in'})).toBeTruthy()});
test('private race creation persists a local lobby and navigates there',async()=>{mount('/private');expect(screen.getByText(/Démo locale/)).toBeTruthy();fireEvent.change(screen.getByLabelText('Nom de la course'),{target:{value:'Amis du soir'}});fireEvent.change(screen.getByLabelText('Langue du texte'),{target:{value:'EN'}});fireEvent.click(screen.getByRole('button',{name:/Créer le salon/}));await waitFor(()=>expect(navigation.push).toHaveBeenCalled());const stored=JSON.parse(localStorage.getItem('guepard-privateRaces'));expect(stored[0].name.fr).toBe('Amis du soir');expect(stored[0].language).toBe('EN');expect(stored[0].private).toBe(true);expect(navigation.push).toHaveBeenLastCalledWith('/race/'+stored[0].id)});
test('race errors, completion, local results and replay',async()=>{mount('/race/canopy');const start=await screen.findByRole('button',{name:/Lancer la course/});fireEvent.click(start);const input=screen.getByRole('textbox');fireEvent.change(input,{target:{value:'X'}});expect(document.querySelector('.incorrect')).not.toBeNull();fireEvent.change(input,{target:{value:''}});let value='';for(const ch of raceService.text('FR')){value+=ch;fireEvent.change(input,{target:{value}})}expect(screen.getByText(/Belle course/)).toBeTruthy();await waitFor(()=>expect(JSON.parse(localStorage.getItem('guepard-results'))).toHaveLength(1));fireEvent.click(screen.getByRole('button',{name:/Rejouer/}));expect(input.value).toBe('');expect(input.disabled).toBe(false)});
test('local private lobbies survive a reload and do not show fake opponents',async()=>{const race=raceService.createPrivate({name:'Ma course',language:'FR'});localStorage.setItem('guepard-privateRaces',JSON.stringify([race]));mount('/race/'+race.id);await screen.findByRole('button',{name:/Lancer la course/});expect(screen.getByText(race.code)).toBeTruthy();expect(screen.queryByText(/Coco/)).toBeNull()});
test('night mode closes every animal and restores daytime artwork',()=>{const {container}=mount();const sky=container.querySelector('.scene-background img'),giraffe=container.querySelector('.giraffe-full');expect(sky.getAttribute('src')).toBe('/assets/relief-background.png');fireEvent.click(screen.getByRole('button',{name:'Changer le thème'}));expect(sky.getAttribute('src')).toBe('/assets/jungle-blue-night.png');expect(giraffe.getAttribute('src')).toBe('/assets/giraffe-night.png');expect(container.querySelectorAll('.scene-animal[data-sleeping="true"]')).toHaveLength(6);expect(container.querySelector('.footer-cheetah').getAttribute('data-sleeping')).toBe('true');expect(container.querySelector('.board-ropes')).not.toBeNull();fireEvent.click(screen.getByRole('button',{name:'Changer le thème'}));expect(sky.getAttribute('src')).toBe('/assets/relief-background.png');expect(giraffe.getAttribute('src')).toBe('/assets/giraffe-full.png');expect(container.querySelectorAll('.scene-animal[data-sleeping="true"]')).toHaveLength(0)});
