import React from 'react';
import {jest,test,expect} from '@jest/globals';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {SiteProvider} from '../src/components/SiteContext';
import Site from '../src/components/Site';
import {raceService} from '../src/data';
import {lobbyRequest} from '../src/services/lobbies';
jest.mock('../src/services/lobbies',()=>({...jest.requireActual('../src/services/lobbies'),lobbyRequest:jest.fn()}));
const mockNavigation={path:'/',push:jest.fn(),replace:jest.fn()};
jest.mock('next/navigation',()=>({usePathname:()=>mockNavigation.path,useRouter:()=>({push:mockNavigation.push,replace:mockNavigation.replace})}));
jest.mock('next/link',()=>({__esModule:true,default:({children,href,...props})=><a href={href} {...props}>{children}</a>}));
function mount(path='/'){mockNavigation.path=path;return render(<SiteProvider><Site/></SiteProvider>)}
test('home has one scene, three real board links and preserved art',()=>{const {container}=mount();expect(container.querySelectorAll('main section')).toHaveLength(1);expect([...container.querySelector('#app').children].map(el=>el.tagName)).toEqual(['HEADER','MAIN','FOOTER']);expect(screen.getByRole('link',{name:/Créer une course privée/}).getAttribute('href')).toBe('/private');expect(screen.getByRole('link',{name:/Parcourir les courses$/}).getAttribute('href')).toBe('/races');expect(container.querySelector('.sleeping-cheetah')).not.toBeNull();expect(container.querySelector('header img').getAttribute('src')).toBe('/assets/guepard-logo.png')});
test('FR/EN, night mode, demo login, settings and logout',async()=>{mount('/login');fireEvent.click(screen.getByRole('button',{name:'Choisir la langue'}));expect(screen.getByRole('button',{name:'Continue with Discord'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Change theme'}));await waitFor(()=>expect(document.documentElement.dataset.theme).toBe('dark'));fireEvent.click(screen.getByRole('button',{name:'Continue with GitHub'}));await screen.findByText(/GitHub login is not configured/);fireEvent.click(screen.getByRole('button',{name:/Explore the demo account/}));expect(screen.getByText('Demo account')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Settings',hidden:true}));fireEvent.change(screen.getByLabelText('Your nickname'),{target:{value:'Jungle'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));expect(screen.getByText('Jungle')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Log out',hidden:true}));expect(screen.getAllByRole('link',{name:'Log in',exact:true}).length).toBeGreaterThan(0)});
test('private creation asks the server for a shared lobby and navigates there',async()=>{lobbyRequest.mockResolvedValueOnce({room:{code:'K7M4AB'}});mount('/private');fireEvent.change(screen.getByLabelText('Nom de la course'),{target:{value:'Amis du soir'}});fireEvent.change(screen.getByLabelText('Langue du texte'),{target:{value:'EN'}});fireEvent.click(screen.getByRole('button',{name:/Créer le salon/}));await waitFor(()=>expect(mockNavigation.push).toHaveBeenLastCalledWith('/lobby/K7M4AB'));expect(lobbyRequest).toHaveBeenCalledWith(null,expect.objectContaining({action:'create',name:'Amis du soir',language:'EN',visibility:'semi'}))});
test('race errors, completion, local results and replay',async()=>{mount('/race/canopy');const start=await screen.findByRole('button',{name:/Lancer la course/});fireEvent.click(start);const input=screen.getByRole('textbox');fireEvent.change(input,{target:{value:'X'}});expect(document.querySelector('.incorrect')).not.toBeNull();fireEvent.change(input,{target:{value:''}});let value='';for(const ch of raceService.text('FR')){value+=ch;fireEvent.change(input,{target:{value}})}expect(screen.getByText(/Belle course/)).toBeTruthy();await waitFor(()=>expect(JSON.parse(localStorage.getItem('guepard-results'))).toHaveLength(1));fireEvent.click(screen.getByRole('button',{name:/Rejouer/}));expect(input.value).toBe('');expect(input.disabled).toBe(false)});
test('local private lobbies survive a reload and do not show fake opponents',async()=>{const race=raceService.createPrivate({name:'Ma course',language:'FR'});localStorage.setItem('guepard-privateRaces',JSON.stringify([race]));mount('/race/'+race.id);await screen.findByRole('button',{name:/Lancer la course/});expect(screen.getByText(race.code)).toBeTruthy();expect(screen.queryByText(/Coco/)).toBeNull()});
test('night mode closes every animal and restores daytime artwork',()=>{const {container}=mount();const sky=container.querySelector('.scene-background img'),giraffe=container.querySelector('.giraffe-full');expect(sky.getAttribute('src')).toBe('/assets/relief-background.png');fireEvent.click(screen.getByRole('button',{name:'Changer le thème'}));expect(sky.getAttribute('src')).toBe('/assets/jungle-blue-night.png');expect(giraffe.getAttribute('src')).toBe('/assets/giraffe-night.png');expect(container.querySelectorAll('.scene-animal[data-sleeping="true"]')).toHaveLength(6);expect(container.querySelector('.footer-cheetah').getAttribute('data-sleeping')).toBe('true');expect(container.querySelector('.board-ropes')).not.toBeNull();fireEvent.click(screen.getByRole('button',{name:'Changer le thème'}));expect(sky.getAttribute('src')).toBe('/assets/relief-background.png');expect(giraffe.getAttribute('src')).toBe('/assets/giraffe-full.png');expect(container.querySelectorAll('.scene-animal[data-sleeping="true"]')).toHaveLength(0)});

test('signup validates confirmation and never persists credentials',async()=>{const {container}=mount('/signup');fireEvent.change(screen.getByLabelText('Nom d’utilisateur'),{target:{value:'GuépardTest'}});fireEvent.change(screen.getByLabelText('Mot de passe',{exact:true}),{target:{value:'demo-secret-42'}});fireEvent.change(screen.getByLabelText('Confirmer le mot de passe'),{target:{value:'different'}});fireEvent.click(screen.getByRole('button',{name:/Créer mon compte/}));expect(screen.getByText('Les mots de passe ne correspondent pas.')).toBeTruthy();fireEvent.change(screen.getByLabelText('Confirmer le mot de passe'),{target:{value:'demo-secret-42'}});fireEvent.click(screen.getByRole('button',{name:/Créer mon compte/}));await screen.findByText(/Formulaire validé/);expect(JSON.stringify(localStorage)).not.toContain('demo-secret-42');expect(screen.getByLabelText('Mot de passe',{exact:true}).value).toBe('');expect(container.querySelectorAll('.auth-friend:not(.auth-paws)')).toHaveLength(4);expect(container.querySelector('.auth-top-cheetah')).not.toBeNull();expect(screen.getByRole('link',{name:/Jouer en invité/}).getAttribute('href')).toBe('/races')});
test('login password visibility and required field feedback',()=>{mount('/login');fireEvent.click(screen.getByRole('button',{name:'Se connecter',exact:true}));expect(screen.getAllByText('Ce champ est obligatoire.')).toHaveLength(2);fireEvent.click(screen.getByRole('button',{name:'Afficher le mot de passe'}));expect(screen.getByLabelText('Mot de passe',{exact:true}).type).toBe('text');fireEvent.click(screen.getByRole('button',{name:'Masquer le mot de passe'}));expect(screen.getByLabelText('Mot de passe',{exact:true}).type).toBe('password')});

test('participant sees synchronized settings but cannot edit or start',async()=>{sessionStorage.setItem('guepard-lobby-K7M4AB','member-token');lobbyRequest.mockResolvedValue({room:{code:'K7M4AB',name:'Amis',hostId:'host',me:'guest',isHost:false,phase:'waiting',revision:0,visibility:'semi',language:'FR',people:[{id:'host',name:'Alex',role:'player',avatar:'🐆'},{id:'guest',name:'Sam',role:'spectator',avatar:'🦜'}],settings:{textType:'story',length:50,punctuation:true,accents:true,numbers:false,blockErrors:false,bots:1,difficulty:'expert',timeLimit:120}}});mount('/lobby/K7M4AB');await screen.findByText(/En attente du lancement/);expect(screen.getByLabelText('Longueur').closest('fieldset').disabled).toBe(true);expect(screen.queryByRole('button',{name:/Démarrer la course/})).toBeNull();expect(screen.queryByRole('button',{name:/Retirer/})).toBeNull();expect(screen.getByText('Bot Expert 1')).toBeTruthy()});
