'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useSite} from './SiteContext';
import {AnimalPicker} from './AnimalAvatar';
import {authService,validateCredentials} from '../services/auth';
type AuthErrors=Partial<Record<'username'|'password'|'confirmation',string>>;
const labels={fr:{login:'Connexion',signup:'Inscription',welcome:'De retour dans la jungle.',join:'Votre aventure commence ici.',intro:'Vos doigts ont des courses à gagner.',signupIntro:'Un pseudo, un clavier. À vous la jungle.',discord:'Continuer avec Discord',github:'Continuer avec GitHub',or:'ou',username:"Nom d’utilisateur",password:'Mot de passe',confirm:'Confirmer le mot de passe',show:'Afficher le mot de passe',hide:'Masquer le mot de passe',showConfirm:'Afficher la confirmation',hideConfirm:'Masquer la confirmation',submit:'Se connecter',create:'Créer mon compte',guest:'Jouer en invité',demo:'Démonstration',demoText:'Connexion et inscription en aperçu : aucun compte réel ne sera créé.',usernameHint:'3 caractères minimum.',passwordHint:'8 caractères minimum.',required:'Ce champ est obligatoire.',usernameShort:'Choisissez un pseudo de 3 caractères minimum.',passwordShort:'Utilisez au moins 8 caractères.',mismatch:'Les mots de passe ne correspondent pas.',preview:'Formulaire validé. Aucun compte réel n’a été créé et aucun mot de passe n’est enregistré.',provider:'La connexion avec {provider} n’est pas encore configurée. Utilisez votre nom d’utilisateur et votre mot de passe.',enterDemo:'Explorer le compte de démonstration',loading:'Un instant…',privacy:'Confidentialité',back:'Retour à la jungle'},en:{login:'Log in',signup:'Sign up',welcome:'Back in the jungle.',join:'Your adventure starts here.',intro:'Your fingers have races to win.',signupIntro:'A nickname, a keyboard. The jungle is yours.',discord:'Continue with Discord',github:'Continue with GitHub',or:'or',username:'Username',password:'Password',confirm:'Confirm password',show:'Show password',hide:'Hide password',showConfirm:'Show confirmation',hideConfirm:'Hide confirmation',submit:'Log in',create:'Create my account',guest:'Play as a guest',demo:'Demo',demoText:'Login and sign-up preview: no real account will be created.',usernameHint:'At least 3 characters.',passwordHint:'At least 8 characters.',required:'This field is required.',usernameShort:'Choose a username with at least 3 characters.',passwordShort:'Use at least 8 characters.',mismatch:'The passwords do not match.',preview:'Form validated. No real account was created and no password is stored.',provider:'{provider} login is not configured yet. Use your username and password.',enterDemo:'Explore the demo account',loading:'One moment…',privacy:'Privacy',back:'Back to the jungle'}};
function ProviderIcon({type}){return type==='discord'?<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M19.7 5.4a18 18 0 0 0-4.4-1.3l-.6 1.2a16 16 0 0 0-5.4 0l-.6-1.2a18 18 0 0 0-4.4 1.3C1.5 9.4.7 13.3 1.1 17a18 18 0 0 0 5.4 2.7l1.1-1.8-1.7-.8.4-.3a12.7 12.7 0 0 0 11.4 0l.4.3-1.7.8 1.1 1.8a18 18 0 0 0 5.4-2.7c.5-4.3-.8-8.2-3.2-11.6ZM8.4 14.8c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Zm7.2 0c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Z"/></svg>:<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .8a11.2 11.2 0 0 0-3.5 21.8c.6.1.8-.2.8-.5v-2.1c-3.4.7-4.1-1.4-4.1-1.4-.5-1.3-1.3-1.7-1.3-1.7-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1.1 1.9 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.4-5.5-6.1 0-1.3.5-2.4 1.2-3.2-.1-.3-.5-1.5.1-3.1 0 0 1-.3 3.3 1.2a11 11 0 0 1 6 0C17.5 4.1 18.5 4.4 18.5 4.4c.6 1.6.2 2.8.1 3.1.8.8 1.2 1.9 1.2 3.2 0 4.7-2.8 5.8-5.5 6.1.5.4.8 1.1.8 2.2v3.1c0 .3.2.6.8.5A11.2 11.2 0 0 0 12 .8Z"/></svg>}
function Eye({open}){return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>{!open&&<path d="m3 3 18 18"/>}</svg>}
export default function Auth({mode='login'}){
 const {state,setAccount,fr}=useSite(),router=useRouter(),l=labels[fr?'fr':'en'],signup=mode==='signup';
 const [animal,setAnimal]=useState('cheetah');
 const [form,setForm]=useState({username:'',password:'',confirmation:''}),[errors,setErrors]=useState<AuthErrors>({}),[visible,setVisible]=useState(false),[confirmVisible,setConfirmVisible]=useState(false),[notice,setNotice]=useState(null),[busy,setBusy]=useState(false);
 function change(key,value){setForm(f=>({...f,[key]:value}));setErrors(e=>({...e,[key]:undefined}));setNotice(null)}
 async function submit(e){e.preventDefault();const next=validateCredentials(form,mode);setErrors(next);if(Object.keys(next).length){document.getElementById('auth-'+Object.keys(next)[0])?.focus();return}setBusy(true);setNotice(null);try{const {user}=await authService.submit({...form,avatar:animal},mode);setForm(f=>({...f,password:'',confirmation:''}));setAccount(user);router.push('/races')}catch(error){setNotice({kind:'error',message:error.message})}finally{setBusy(false)}}
 async function provider(name){setBusy(true);setNotice(await authService.provider(name));setBusy(false)}
 return <main className="auth-page"><div className="auth-scenery" aria-hidden="true"><img src={state.dark?'/assets/jungle-blue-night.webp':'/assets/relief-background.webp'} alt=""/></div><Link className="auth-back" href="/">← {l.back}</Link><div className="auth-stage"><div className="auth-top-cheetah" aria-hidden="true"/><div className="auth-friend auth-monkey" aria-hidden="true"/><div className="auth-friend auth-crocodile" aria-hidden="true"/><div className="auth-friend auth-parrot" aria-hidden="true"/><div className="auth-friend auth-elephant" aria-hidden="true"/>{['monkey','crocodile','parrot','elephant'].map(animal=><div key={animal} className={`auth-friend auth-${animal} auth-paws`} aria-hidden="true"/>)}<div className="auth-top-cheetah auth-cheetah-paws" aria-hidden="true"/>
 <section className="auth-card" aria-labelledby="auth-title"><nav className="auth-tabs" aria-label={fr?'Accès au compte':'Account access'}><Link href="/login" className={!signup?'selected':''} aria-current={!signup?'page':undefined}>{l.login}</Link><Link href="/signup" className={signup?'selected':''} aria-current={signup?'page':undefined}>{l.signup}</Link></nav><div className="auth-heading"><h1 id="auth-title">{signup?l.join:l.welcome}</h1><p>{signup?l.signupIntro:l.intro}</p></div>
 <div className="auth-providers grid gap-3"><button type="button" className="auth-provider discord" onClick={()=>provider('discord')} disabled={busy}><ProviderIcon type="discord"/>{l.discord}</button><button type="button" className="auth-provider github" onClick={()=>provider('github')} disabled={busy}><ProviderIcon type="github"/>{l.github}</button></div><div className="auth-divider"><span>{l.or}</span></div>
 <form onSubmit={submit} noValidate className="auth-form grid gap-5"><div><label htmlFor="auth-username">{l.username}</label><input id="auth-username" autoComplete="username" maxLength={24} value={form.username} onChange={e=>change('username',e.target.value)} placeholder="GuépardCurieux" aria-invalid={!!errors.username} aria-describedby={errors.username?'username-error':signup?'username-hint':undefined}/>{errors.username?<p id="username-error" className="auth-error">{l[errors.username]}</p>:signup&&<p id="username-hint" className="auth-hint">{l.usernameHint}</p>}</div>
 <div><label htmlFor="auth-password">{l.password}</label><div className="auth-password"><input id="auth-password" type={visible?'text':'password'} autoComplete={signup?'new-password':'current-password'} value={form.password} onChange={e=>change('password',e.target.value)} placeholder="••••••••" aria-invalid={!!errors.password} aria-describedby={errors.password?'password-error':signup?'password-hint':undefined}/><button type="button" aria-label={visible?l.hide:l.show} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}><Eye open={visible}/></button></div>{errors.password?<p id="password-error" className="auth-error">{l[errors.password]}</p>:signup&&<p id="password-hint" className="auth-hint">{l.passwordHint}</p>}</div>
 {signup&&<div><label htmlFor="auth-confirmation">{l.confirm}</label><div className="auth-password"><input id="auth-confirmation" type={confirmVisible?'text':'password'} autoComplete="new-password" value={form.confirmation} onChange={e=>change('confirmation',e.target.value)} aria-invalid={!!errors.confirmation} aria-describedby={errors.confirmation?'confirmation-error':undefined}/><button type="button" aria-label={confirmVisible?l.hideConfirm:l.showConfirm} aria-pressed={confirmVisible} onClick={()=>setConfirmVisible(v=>!v)}><Eye open={confirmVisible}/></button></div>{errors.confirmation&&<p id="confirmation-error" className="auth-error">{l[errors.confirmation]}</p>}</div>}
 {signup&&<AnimalPicker value={animal} onChange={setAnimal} fr={fr}/>}<button className="button primary auth-submit" disabled={busy}>{busy?l.loading:signup?l.create:l.submit}<span aria-hidden="true">→</span></button></form>
 {notice&&<div className="auth-notice" role={notice.kind==='error'?'alert':'status'}><p>{notice.kind==='error'?notice.message:l.provider.replace('{provider}',notice.provider==='discord'?'Discord':'GitHub')}</p></div>}
 <Link className="auth-guest" href="/races">{l.guest} <span aria-hidden="true">→</span></Link><Link className="auth-privacy" href="/privacy">{l.privacy}</Link></section></div></main>
}
