'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useSite} from './SiteContext';
import {AnimalAvatar} from './AnimalAvatar';
export function Header(){const {state,save,signOut,c,fr,setModal}=useSite(),path=usePathname(),router=useRouter();return <header className="canopy-header"><Link className="brand" href="/"><img src="/assets/guepard-logo.webp" alt="" fetchPriority="high" decoding="async"/><span>GUÉPARD</span></Link><nav className="main-navigation" aria-label="Navigation"><Link href="/" className={path==='/'?'active':''}>{c.home}</Link><Link href="/how" className={path==='/how'?'active':''}>{fr?'Comment jouer':'How to play'}</Link><Link href="/races" aria-current={path==='/races'?'page':undefined} className={`nav-races ${path==='/races'?'active':''}`}>{fr?'Parcourir les courses':'Browse races'}</Link>{!state.user&&<Link className="results-stats-nav" href="/stats">{c.stats}</Link>}{state.user&&<Link href="/stats" className={path==='/stats'?'active':''}>{c.stats}</Link>}</nav><div className="controls">{state.user?<details className="account"><summary><AnimalAvatar animal={state.avatar}/> <span>{state.name}</span></summary><div><small>{c.account}</small><Link href="/stats">{c.stats}</Link><button onClick={()=>setModal('settings')}>{c.settings}</button><button onClick={async()=>{await signOut();router.push('/')}}>{c.logout}</button></div></details>:<Link className="login" href="/login">{c.login}</Link>}<button className="language" onClick={()=>save('lang',fr?'en':'fr')} aria-label={c.langLabel}>◎ {state.lang.toUpperCase()}⌄</button><button className="theme" onClick={()=>save('dark',!state.dark)} aria-label={c.themeLabel}>{state.dark?'☀':'☾'}</button></div><img className="header-branch" src="/assets/header-branch.webp" alt="" decoding="async" aria-hidden="true"/></header>}
export function Footer(){const {c,fr,state}=useSite();return <footer className="compact-footer"><div className="footer-cheetah" data-sleeping={state.dark} role="img" aria-label={state.dark?(fr?'Guépard endormi sur le bord du pied de page':'Cheetah asleep on the footer'):(fr?'Guépard appuyé sur le bord du pied de page':'Cheetah resting its paws on the footer')}/><div className="compact-footer-row"><Link className="brand" href="/">GUÉPARD</Link><nav className="essential-links" aria-label={fr?'Liens utiles':'Useful links'}><Link href="/">{c.home}</Link><Link href="/races">{c.browse}</Link><Link href="/how">{fr?'Comment jouer':'How to play'}</Link>{['contact','legal','privacy'].map(x=><Link key={x} href={'/'+x}>{c[x]}</Link>)}</nav></div><small className="compact-copyright">© {new Date().getFullYear()} GUÉPARD</small></footer>}
export function Modal(){const {setModal,state,save,c}=useSite(),ref=useRef<HTMLDialogElement>(null),[name,setName]=useState(state.name);useEffect(()=>{const previous=document.activeElement;ref.current?.showModal();return()=>{if(previous instanceof HTMLElement)previous.focus()}},[]);return <dialog ref={ref} onClose={()=>setModal(null)} aria-labelledby="modal-title"><button className="close" aria-label={c.close} onClick={()=>ref.current?.close()}>×</button><AnimalAvatar animal={state.avatar}/><h2 id="modal-title">{c.settings}</h2><form onSubmit={e=>{e.preventDefault();save('name',name.trim()||'GuépardCurieux');setModal(null)}}><p>{c.account}</p><label htmlFor="setting-name">{c.nickname}</label><input id="setting-name" maxLength={24} value={name} onChange={e=>setName(e.target.value)}/><button className="button primary">{c.save}</button></form></dialog>}
