'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useSite} from './SiteContext';
import {lobbyRequest,lobbyToken} from '../services/lobbies';
const difficulty={easy:'Débutant',medium:'Intermédiaire',expert:'Expert'};
const visibility={public:'🌿 Publique',semi:'🔒 Semi-publique',private:'🔒 Privée'};
export default function Lobby({code}){
 const {state}=useSite(),router=useRouter(),[room,setRoom]=useState(null),[joining,setJoining]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(''),[nickname,setNickname]=useState(''),[role,setRole]=useState('player');
 const revision=useRef(-1);
 function accept(next){if(next&&next.revision>=revision.current){revision.current=next.revision;setRoom(next)}}
 useEffect(()=>{let active=true;let timer;async function refresh(){if(!lobbyToken(code)){if(active)setJoining(true);return}try{const data=await lobbyRequest(code);if(active){accept(data.room);setJoining(false);setError('')}}catch(e){if(active){setError(e.message);if(e.status===403||e.status===404){setRoom(null);setJoining(true);sessionStorage.removeItem('guepard-lobby-'+code);return}}}if(active)timer=setTimeout(refresh,1000)}refresh();return()=>{active=false;clearTimeout(timer)}},[code,joining]);
 async function act(body){setBusy(true);setError('');try{const data=await lobbyRequest(code,body);accept(data.room);if(body.action==='join')setJoining(false);if(body.action==='leave'){sessionStorage.removeItem('guepard-lobby-'+code);router.push('/races')}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function copy(kind){try{await navigator.clipboard.writeText(kind==='code'?code:window.location.origin+'/lobby/'+code);setCopied(kind==='code'?'Code copié !':'Lien copié !');setTimeout(()=>setCopied(''),2500)}catch{setCopied('Copie impossible. Sélectionnez le code ci-dessus.')}}
 if(!room)return <main className="lobby-page"><div className="lobby-shell"><Link href="/races" className="text-link">← Toutes les courses</Link><section className="lobby-paper lobby-entry"><span className="eyebrow">LE POINT DE RENCONTRE</span><h1>Course #{code}</h1>{error&&<p role="alert" className="lobby-error">{error}</p>}{joining?<form onSubmit={e=>{e.preventDefault();act({action:'join',nickname:nickname.trim()||state.name,avatar:state.avatar,role})}}><p>La jungle vous attend. Entrez dans le salon.</p><label htmlFor="lobby-name">Votre pseudo</label><input id="lobby-name" value={nickname||state.name} onChange={e=>setNickname(e.target.value)} maxLength={24} required/><label htmlFor="join-role">Votre rôle</label><select id="join-role" value={role} onChange={e=>setRole(e.target.value)}><option value="player">Joueur — je participe</option><option value="spectator">Spectateur — je regarde</option></select><button className="button primary" disabled={busy}>Rejoindre le salon →</button></form>:<p role="status">Ouverture du salon…</p>}</section></div></main>;
 const host=room.people.find(p=>p.id===room.hostId),me=room.people.find(p=>p.id===room.me),s=room.settings;
 const update=(key,value)=>act({action:'settings',settings:{[key]:value}});
 return <main className="lobby-page"><div className="lobby-shell"><div className="lobby-breadcrumb"><Link href="/races">← Toutes les courses</Link><span><i/> Salon partagé</span></div><div className="lobby-heading"><div><div className="eyebrow">{room.phase==='waiting'?'ON SE RETROUVE AU DÉPART':'À VOUS DE JOUER'}</div><h1>Course <span>#{room.code}</span></h1><p>{room.name} <span>·</span> Hôte : {host?.name}</p></div><div className="lobby-share"><span className="lobby-visibility">{visibility[room.visibility]}</span><button className="lobby-copy" onClick={()=>copy('code')}>⧉ Copier le code</button><button className="text-link" onClick={()=>copy('link')}>Copier le lien ↗</button><span className="lobby-copy-status" role="status">{copied}</span></div></div>{error&&<p role="alert" className="lobby-error">{error}</p>}
 <div className="lobby-columns"><section className="lobby-paper lobby-participants"><div className="lobby-card-title"><span className="lobby-symbol">♧</span><h2>Participants <span>{room.people.length+s.bots}</span></h2></div><p className="lobby-caption">La petite troupe au départ.</p><ul className="lobby-people">{room.people.map(p=><li key={p.id}><span className="lobby-avatar" aria-hidden="true">{p.avatar}</span><div><strong>{p.name} {p.id===room.me&&<small>(vous)</small>}</strong><span>{p.id===room.hostId?'♛ Hôte · ':''}{p.role==='spectator'?'Spectateur':'Joueur'}</span></div>{room.isHost&&p.id!==room.hostId&&room.phase==='waiting'?<button className="lobby-remove" disabled={busy} aria-label={'Retirer '+p.name} onClick={()=>act({action:'kick',id:p.id})}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 10v7m4-7v7"/></svg></button>:<span className="lobby-person-dot"/>}</li>)}{Array.from({length:s.bots},(_,i)=><li key={'bot'+i}><span className="lobby-avatar bot">🤖</span><div><strong>Bot {difficulty[s.difficulty]} {i+1}</strong><span>Joueur automatique</span></div>{room.isHost&&room.phase==='waiting'&&<button className="lobby-remove" disabled={busy} aria-label={'Retirer le bot '+(i+1)} onClick={()=>update('bots',s.bots-1)}>×</button>}</li>)}</ul><div className="lobby-role"><label htmlFor="my-role">Je rejoins la course comme</label><select id="my-role" disabled={busy||room.phase!=='waiting'} value={me?.role} onChange={e=>act({action:'role',role:e.target.value})}><option value="player">Joueur</option><option value="spectator">Spectateur</option></select></div><div className="lobby-tip"><span>🌱</span><p>{room.visibility==='public'?'Votre salon est visible dans les courses publiques.':'Invitez vos amis avec le code ou le lien. Ce salon n’apparaît pas dans la liste publique.'}</p></div></section>
 <section className="lobby-paper lobby-settings"><div className="lobby-card-title"><span className="lobby-symbol">☷</span><h2>Paramètres</h2><span className="lobby-access">{room.isHost?'Vous êtes l’hôte':'Lecture seule'}</span></div><p className="lobby-caption">{room.isHost?'Préparez une course à votre rythme.':'Les choix de l’hôte s’affichent ici en direct.'}</p><fieldset disabled={!room.isHost||busy||room.phase!=='waiting'}><legend className="sr-only">Paramètres de la course</legend><div className="lobby-fields"><div><label htmlFor="text-type">Type de texte</label><select id="text-type" value={s.textType} onChange={e=>update('textType',e.target.value)}><option value="story">Petite histoire de jungle</option><option value="words">Liste de mots</option></select></div><div><label htmlFor="text-length">Longueur</label><select id="text-length" value={s.length} onChange={e=>update('length',Number(e.target.value))}>{[25,50,100,200].map(n=><option key={n} value={n}>{n} mots</option>)}</select></div></div><div className="lobby-options">{[['punctuation','Ponctuation','Les points, virgules et apostrophes.'],['accents','Accents','Un peu de précision : é, è, à…'],['numbers','Chiffres','Quelques nombres dans le texte.'],['blockErrors','Les erreurs bloquent la frappe','Corrigez chaque erreur pour continuer.']].map(([key,label,hint])=><label className="lobby-toggle" key={key}><span><strong>{label}</strong><small>{hint}</small></span><input type="checkbox" role="switch" checked={s[key]} onChange={e=>update(key,e.target.checked)}/></label>)}</div><div className="lobby-fields lobby-bot-fields"><div><label htmlFor="bot-count">Nombre de bots</label><select id="bot-count" value={s.bots} onChange={e=>update('bots',Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'Aucun bot':n+' bot'+(n>1?'s':'')}</option>)}</select></div><div><label htmlFor="bot-difficulty">Difficulté des bots</label><select id="bot-difficulty" value={s.difficulty} onChange={e=>update('difficulty',e.target.value)}>{Object.entries(difficulty).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div><label htmlFor="time-limit">Limite de temps</label><select id="time-limit" value={s.timeLimit} onChange={e=>update('timeLimit',Number(e.target.value))}><option value={0}>Sans limite</option><option value={60}>1 minute</option><option value={120}>2 minutes</option><option value={300}>5 minutes</option></select></div><div className="lobby-language"><small>Langue du texte</small><strong>{room.language==='FR'?'🇫🇷 Français':'🇬🇧 English'}</strong></div></div></fieldset><p className="lobby-sync">↻ Paramètres synchronisés pour tout le salon.</p></section></div>
 {room.phase==='running'?<SharedRace key={room.startedAt} room={room} me={me}/>:<div className="lobby-launch"><div><strong>{room.isHost?'Tout le monde est là ?':'Installez-vous, le départ approche.'}</strong><p>{room.isHost?'Vous donnez le départ à toute la troupe.':'Les paramètres restent visibles pendant l’attente.'}</p></div>{room.isHost?<button className="button primary" disabled={busy||!room.people.some(p=>p.role==='player')} onClick={()=>act({action:'start'})}>Démarrer la course <span>→</span></button>:<div className="lobby-wait" role="status"><span className="lobby-wait-dot"/> En attente du lancement par l’hôte…</div>}</div>}
 <div className="lobby-bottom"><span>16 places · {room.language==='FR'?'Français':'English'} · {s.length} mots</span>{room.isHost&&room.phase==='running'&&<button className="text-link" disabled={busy} onClick={()=>act({action:'reset'})}>Revenir au salon</button>}<button className="text-link" disabled={busy} onClick={()=>act({action:'leave'})}>{room.isHost?'Fermer le salon':'Quitter le salon'} ↗</button></div></div></main>
}
function SharedRace({room,me}){const {save}=useSite(),[now,setNow]=useState(Date.now()),[value,setValue]=useState(''),[errors,setErrors]=useState(0),[finished,setFinished]=useState(false),saved=useRef(false);const countdown=Math.max(0,Math.ceil((room.startedAt-now)/1000)),elapsed=Math.max(0,(now-room.startedAt)/1000),expired=room.settings.timeLimit>0&&elapsed>=room.settings.timeLimit,spectator=me?.role==='spectator';useEffect(()=>{if(finished||expired)return;const timer=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(timer)},[finished,expired]);const correct=[...value].filter((c,i)=>c===room.text[i]).length,speed=Math.round(correct/5/(Math.max(1,elapsed)/60));useEffect(()=>{if((finished||expired)&&!saved.current&&!spectator){saved.current=true;save('results',list=>[...list,{speed,accuracy:Math.round(correct/Math.max(1,value.length+errors)*100),date:Date.now()}])}},[finished,expired,spectator,speed,correct,value.length,errors,save]);function type(e){const next=e.target.value.slice(0,room.text.length);if(room.settings.blockErrors&&!room.text.startsWith(next)){setErrors(n=>n+1);return}setValue(next);if(next===room.text)setFinished(true)}return <section className="lobby-paper lobby-game"><div className="lobby-card-title"><h2>{countdown?'Départ dans '+countdown+'…':finished?'Bravo, course terminée !':expired?'Temps écoulé':spectator?'La course est en cours':'À vos claviers !'}</h2><span>{Math.floor(elapsed)} s · {speed} mots/min</span></div><p className="target">{[...room.text].map((ch,i)=><span key={i} className={i<value.length?(ch===value[i]?'correct':'incorrect'):''}>{ch}</span>)}</p>{!spectator&&<textarea aria-label="Texte de la course" disabled={countdown>0||finished||expired} value={value} onChange={type} onPaste={e=>e.preventDefault()} placeholder="Tapez le texte ici…" spellCheck={false} autoCapitalize="off" autoCorrect="off"/>}{spectator&&<p>Vous êtes spectateur. Le texte et le chronomètre sont partagés avec les joueurs.</p>}{Array.from({length:room.settings.bots},(_,i)=><div className="lobby-bot-progress" key={i}><span>🤖 Bot {difficulty[room.settings.difficulty]} {i+1}</span><progress aria-label={'Progression du bot '+(i+1)} max={room.text.length} value={Math.min(room.text.length,Math.max(0,Math.min(elapsed,room.settings.timeLimit||elapsed))*({easy:25,medium:50,expert:85}[room.settings.difficulty]+i)*5/60)}/></div>)}</section>}
