'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useSite} from './SiteContext';
import {raceService} from '../data';
import {AnimalAvatar,AnimalPicker} from './AnimalAvatar';
import {animalFor} from '../lib/animals';
import {roomRequest} from '../lib/room-client';
export function Nickname(){const {state,save,c,fr}=useSite();return <div><label htmlFor="nickname">{c.nickname}</label><input id="nickname" maxLength={40} value={state.name} onChange={e=>save('name',e.target.value)} onBlur={()=>{if(!state.name.trim())save('name','GuépardCurieux')}}/>{state.user?<AnimalPicker value={state.avatar} onChange={value=>save('avatar',value)} fr={fr}/>:<div className="guest-animal"><AnimalAvatar animal="cheetah"/><small>{fr?'Ton avatar invité : Guépard':'Your guest avatar: Cheetah'}</small></div>}</div>}
const raceWorlds={
 canopy:{image:'canopy',fr:{place:'Au sommet des arbres',description:'Prends de la hauteur entre les lianes et les grandes feuilles. Les perroquets donnent le départ.',alt:'Un perroquet et un singe dans une canopée verdoyante, en illustration 3D au feutre.'},en:{place:'Up in the treetops',description:'Climb into the canopy, between vines and giant leaves. The parrots are ready to give the start.',alt:'A parrot and a monkey in a lush canopy, illustrated in 3D with felt-tip textures.'}},
 river:{image:'river',fr:{place:'Une aventure au fil de l’eau',description:'Suis le courant, traverse les cascades et garde le rythme. Un crocodile curieux t’attend sur la rive.',alt:'Un crocodile au bord d’une rivière turquoise, entouré de fougères en 3D au feutre.'},en:{place:'An adventure along the water',description:'Follow the current, pass the waterfalls and find your rhythm. A curious crocodile waits on the riverbank.',alt:'A crocodile beside a turquoise jungle river, with ferns in a handmade 3D marker style.'}},
 sun:{image:'sun',fr:{place:'Sous le soleil doré',description:'Une clairière chaude, des manguiers et un guépard prêt à bondir. La jungle prend les couleurs du soleil.',alt:'Un guépard et un éléphant dans une clairière dorée, illustrés en 3D au feutre.'},en:{place:'Under the golden sun',description:'A warm clearing, mango trees and a cheetah ready to leap. The jungle glows in the afternoon sun.',alt:'A cheetah and an elephant in a golden jungle clearing, illustrated with 3D marker textures.'}}
};
export function RaceCard({race:r,index=0,total=1}){
 const {state,c,fr}=useSite(),world=raceWorlds[r.live?animalFor(r.animal).landscape:r.id]||raceWorlds.canopy,copy=world[state.lang],action=r.state==='running'?c.watch:(fr?'Rejoindre rapidement':'Quick join');
 return <article className={`expedition-card expedition-${world.image}`} style={{'--card-index':index}} aria-labelledby={'expedition-'+r.id}>
  <div className="expedition-copy"><div className="expedition-topline"><span className="expedition-number">{String(index+1).padStart(2,'0')} / {String(total).padStart(2,'0')}</span><span className="expedition-status"><i className={r.state}/>{c[r.state]}</span></div><p className="expedition-place">{copy.place}</p><h2 id={'expedition-'+r.id}>{r.name[state.lang]}</h2><p className="expedition-description">{copy.description}</p><div className="expedition-meta"><span>{r.language==='FR'?'FR · Français':'EN · English'}</span><span>{r.players}{r.max?'/'+r.max:''} {c.players}</span></div><Link className="expedition-join" href={(r.live?'/lobby/':'/race/')+r.id} aria-label={action+' — '+r.name[state.lang]}>{action}<span aria-hidden="true">↗</span></Link><span className="expedition-footnote">{r.live?(fr?'Salon public':'Public lobby'):(fr?'Course de démonstration':'Demo race')}</span></div>
  <div className="expedition-art"><img src={'/assets/race-'+world.image+'.png'} alt={copy.alt} loading={index===0?'eager':'lazy'} width="1536" height="1024"/><span className="expedition-art-label" aria-hidden="true">GUÉPARD <span>✳</span> {fr?'LA JUNGLE T’ATTEND':'THE JUNGLE AWAITS'}</span></div>
 </article>
}
export function Races(){
 const {state,c,fr}=useSite(),[races,setRaces]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[joinCode,setJoinCode]=useState(''),router=useRouter();
 useEffect(()=>{let active=true;Promise.all([raceService.list(),roomRequest(null)]).then(([demo,data])=>{const r=data.rooms.length?data.rooms:demo;return r}).then(r=>{if(active){setRaces(r);setLoading(false)}}).catch(()=>{if(active){setError(fr?'Impossible de charger les courses.':'Could not load races.');setLoading(false)}});return()=>{active=false}},[fr]);
 async function refresh(){setLoading(true);setError('');try{const [demo,data]=await Promise.all([raceService.list(),roomRequest(null)]);setRaces(data.rooms.length?data.rooms:demo)}catch{setError(fr?'Impossible de charger les courses.':'Could not load races.')}finally{setLoading(false)}}
 return <main className="expeditions-page"><div className="expeditions-intro"><div><p className="expeditions-eyebrow">{fr?'LES COURSES GUÉPARD':'GUÉPARD RACES'}</p><h1>{fr?'À chacun son':'Find your own'}<br/><em>{fr?'coin de jungle.':'corner of the jungle.'}</em></h1><p className="expeditions-lead">{fr?'Choisis ton décor. Installe-toi au départ. À tes doigts de jouer.':'Pick your scenery. Head to the start. Let your fingers do the racing.'}</p></div><div className="expeditions-intro-actions"><Link href="/private">{fr?'Créer une course privée':'Create a private race'} <span>→</span></Link></div></div>
 <form className="course-code-entry" onSubmit={async e=>{e.preventDefault();setError('');try{const {id}=await roomRequest(null,{action:'resolve',code:joinCode});router.push('/lobby/'+id+'?code='+encodeURIComponent(joinCode.toUpperCase()))}catch(e){setError(e.message)}}}><label htmlFor="public-join-code">{fr?'Tu as un code ?':'Have a code?'}</label><input id="public-join-code" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} maxLength={8} required placeholder="Code du salon"/><button className="wood-small-button">{fr?'Rejoindre':'Join'}</button></form><div className="expeditions-toolbar"><span className="expeditions-scroll-hint"><span aria-hidden="true">↓</span> {fr?'Fais défiler, explore la jungle':'Scroll to explore the jungle'}</span><div className="expeditions-tools"><details className="expeditions-identity"><summary><AnimalAvatar animal={state.avatar}/> {state.name} <span>⌄</span></summary><div className="expeditions-identity-panel"><Nickname/></div></details><button className="expeditions-refresh" onClick={refresh} disabled={loading} aria-label={c.refresh}>↻</button></div></div>
 {error&&<p role="alert">{error}</p>}{loading&&!races.length?<p role="status">{c.loading}</p>:races.length?<section className="expedition-stack" aria-label={c.races}>{races.map((r,index)=><RaceCard key={r.id} race={r} index={index} total={races.length}/>)}</section>:!error&&<div className="empty"><h2>{c.empty}</h2><p>{c.emptyText}</p></div>}
 <div className="expeditions-end"><span aria-hidden="true">✳</span><p>{fr?'La prochaine aventure commence au bout de tes doigts.':'Your next adventure starts at your fingertips.'}</p><small>{c.demoNote}</small></div></main>
}
