'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {raceService} from '../data';
import {useSite} from './SiteContext';
export default function RaceGame({id}){const {state,save,c,fr,ready}=useSite(),[publicRaces,setPublicRaces]=useState(null),[value,setValue]=useState(''),[phase,setPhase]=useState('waiting'),[elapsed,setElapsed]=useState(0),[counts,setCounts]=useState({errors:0,keys:0}),began=useRef(null),field=useRef(null);useEffect(()=>{let active=true;raceService.list().then(r=>{if(active)setPublicRaces(r)});return()=>{active=false}},[]);const race=state.privateRaces.find(r=>r.id===id)||publicRaces?.find(r=>r.id===id);const text=race?raceService.text(race.language):'';
 useEffect(()=>{if(phase!=='playing')return;const timer=setInterval(()=>{if(began.current)setElapsed((Date.now()-began.current)/1000)},250);return()=>clearInterval(timer)},[phase]);
 useEffect(()=>{if(phase==='playing')field.current?.focus()},[phase]);
 function start(){setValue('');setCounts({errors:0,keys:0});setElapsed(0);began.current=null;setPhase('playing')}
 function type(e){const input=e.target.value.slice(0,text.length);if(!began.current)began.current=Date.now();let next={...counts};if(input.length>value.length){for(let i=value.length;i<input.length;i++){next.keys++;if(input[i]!==text[i])next.errors++}}setCounts(next);setValue(input);if(input===text){const seconds=Math.max(.001,(Date.now()-began.current)/1000),speed=Math.round(input.length/5/(seconds/60)),accuracy=next.keys?Math.max(0,Math.round((1-next.errors/next.keys)*100)):100;setElapsed(seconds);setPhase('finished');save('results',list=>[...list,{speed,accuracy,date:Date.now()}])}}
 if(!ready||!publicRaces)return <main className="inner" role="status">{c.loading}</main>;
 if(!race)return <main className="inner"><h1>{fr?'Salon introuvable':'Lobby not found'}</h1><p>{fr?'Les salons privés de démonstration sont disponibles uniquement sur l’appareil qui les a créés.':'Private demo lobbies are only available on the device that created them.'}</p><Link className="button primary mt-6" href="/races">{c.back}</Link></main>;
 const speed=elapsed?Math.round(value.length/5/(elapsed/60)):0,accuracy=counts.keys?Math.max(0,Math.round((1-counts.errors/counts.keys)*100)):100;
 return <main className="inner lobby"><Link className="text-link" href="/races">← {c.back}</Link><div className="eyebrow">{c.lobby}</div><h1>{race.animal} {race.name[state.lang]}</h1><p>{race.private?(fr?'Salon privé local · Aucun autre joueur connecté.':'Local private lobby · No other connected players.'):c.demoNote}</p>{race.private&&<div className="private-panel mt-6 rounded-xl p-5"><p>{fr?'Code du salon de démonstration':'Demo lobby code'}</p><p className="private-code mt-2">{race.code}</p><p className="private-notice mt-2">{fr?'Identifiant local, non utilisable comme invitation en ligne.':'Local identifier, not an online invitation.'}</p></div>}<section className="game"><div className="scoreboard"><div><strong>{speed}</strong><span>{c.speed}</span></div><div><strong>{accuracy}%</strong><span>{c.accuracy}</span></div><div><strong>{Math.floor(elapsed)}</strong><span>{c.time}</span></div></div><div className="track"><span>{state.avatar} {state.name||'GuépardCurieux'} · {c.you}</span><progress max="100" value={value.length/text.length*100} aria-label={c.progress}/></div>{!race.private&&<div className="opponents">🦜 Coco &nbsp; 🐊 Kiwi <small>({c.sample})</small></div>}<p className="target">{[...text].map((ch,i)=><span key={i} className={i<value.length?(ch===value[i]?'correct':'incorrect'):i===value.length&&phase==='playing'?'cursor':''}>{ch}</span>)}</p><textarea ref={field} value={value} onChange={type} onPaste={e=>e.preventDefault()} placeholder={c.type} aria-label={c.type} disabled={phase!=='playing'} spellCheck={false} autoCapitalize="off" autoComplete="off" autoCorrect="off"/><div role="status">{phase==='finished'&&<h2>{c.finish} ✳</h2>}</div>{phase!=='playing'&&<button className="button primary" onClick={start}>{phase==='finished'?c.restart:c.start} →</button>}</section></main>}
