'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useSite} from './SiteContext';
import {raceService} from '../data';
export function Nickname(){const {state,save,c}=useSite();return <div><label htmlFor="nickname">{c.nickname}</label><input id="nickname" maxLength={24} value={state.name} onChange={e=>save('name',e.target.value)} onBlur={()=>{if(!state.name.trim())save('name','GuépardCurieux')}}/><div className="avatars" aria-label={c.avatar}>{['🐆','🦜','🐊','🦁'].map(a=><button key={a} type="button" onClick={()=>save('avatar',a)} aria-label={a} aria-pressed={state.avatar===a} className={state.avatar===a?'selected':''}>{a}</button>)}</div></div>}
export function RaceCard({race:r}){const {state,c}=useSite();return <article className={`race-card ${r.color}`}><div className="card-top"><span className="animal">{r.animal}</span><span className={`status ${r.state}`}><i/>{c[r.state]}</span></div><h3>{r.name[state.lang]}</h3><div className="race-meta"><span>{r.language==='FR'?'🇫🇷 Français':'🇬🇧 English'}</span><span>♧ {r.players}/{r.max} {c.players}</span></div><Link className="card-join" href={'/race/'+r.id}>{r.state==='running'?c.watch:c.enter}<span>→</span></Link></article>}
export function Races(){const {c,fr}=useSite(),[races,setRaces]=useState([]),[loading,setLoading]=useState(true),router=useRouter();useEffect(()=>{let active=true;raceService.list().then(r=>{if(active){setRaces(r);setLoading(false)}});return()=>{active=false}},[]);const next=races.find(r=>r.state==='waiting');return <main className="inner"><div className="eyebrow">{c.demo}</div><h1>{c.ready}</h1><p>{c.guest}</p><section className="quick-join"><Nickname/><button className="button primary" disabled={!next} onClick={()=>router.push('/race/'+next.id)}>{c.next} →</button></section><div className="section-row"><h2>{c.races}</h2><button className="text-link" onClick={async()=>setRaces(await raceService.list())}>↻ {c.refresh}</button></div><div className="race-grid">{loading?<p role="status">{c.loading}</p>:races.length?races.map(r=><RaceCard key={r.id} race={r}/>):<div className="empty"><h3>{c.empty}</h3><p>{c.emptyText}</p></div>}</div><p className="demo-note"><span>{c.demo}</span> {c.demoNote}</p><Link className="text-link mt-6" href="/private">{fr?'Créer une course privée':'Create a private race'} →</Link></main>}
export function PrivateRace(){const {state,save,c,fr}=useSite(),router=useRouter(),[name,setName]=useState(''),[language,setLanguage]=useState(fr?'FR':'EN');function create(e){e.preventDefault();const race=raceService.createPrivate({name:name.trim(),language});save('privateRaces',list=>[...list,race]);router.push('/race/'+race.id)}return <main className="inner"><div className="eyebrow">{c.demo}</div><h1>{fr?'Créer une course privée':'Create a private race'}</h1><p>{fr?'Préparez votre salon privé de démonstration.':'Set up your private demo lobby.'}</p><form onSubmit={create} className="private-form mt-8 grid max-w-2xl gap-6 rounded-2xl p-6 sm:p-8"><Nickname/><div><label htmlFor="race-name">{fr?'Nom de la course':'Race name'}</label><input id="race-name" required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder={fr?'La course des amis':'Friends’ race'}/></div><div><label htmlFor="race-language">{fr?'Langue du texte':'Text language'}</label><select id="race-language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="FR">Français</option><option value="EN">English</option></select></div><p className="private-notice">{fr?'Démo locale : ce salon reste sur cet appareil. Aucun lien d’invitation ni multijoueur en ligne n’est disponible pour le moment.':'Local demo: this lobby stays on this device. Invitation links and online multiplayer are not available yet.'}</p><button className="button primary justify-self-start" disabled={!name.trim()}>{fr?'Créer le salon':'Create lobby'} →</button></form></main>}
