'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useSite} from './SiteContext';
import {AnimalAvatar,AnimalPicker} from './AnimalAvatar';
import {animalFor} from '../lib/animals';
import {roomRequest} from '../lib/room-client';

export function Nickname(){const {state,save,c,fr}=useSite();return <div><label htmlFor="nickname">{c.nickname}</label><input id="nickname" maxLength={40} value={state.name} onChange={e=>save('name',e.target.value)} onBlur={()=>{if(!state.name.trim())save('name','GuépardCurieux')}}/>{state.user?<AnimalPicker value={state.avatar} onChange={value=>save('avatar',value)} fr={fr}/>:<div className="guest-animal"><AnimalAvatar animal="cheetah"/><small>{fr?'Ton avatar invité : Guépard':'Your guest avatar: Cheetah'}</small></div>}</div>}

export function RaceCard({race:r,index=0,total=1}){const {fr}=useSite(),animal=animalFor(r.animal),action=r.state==='running'?(fr?'Regarder la course':'Watch the race'):(fr?'Rejoindre':'Join');return <article className={`expedition-card expedition-${animal.landscape}`} style={{'--card-index':index}} aria-labelledby={'expedition-'+r.id}><div className="expedition-copy"><div className="expedition-topline"><span className="expedition-number">{String(index+1).padStart(2,'0')} / {String(total).padStart(2,'0')}</span><span className="expedition-status"><i className={r.state}/>{r.state==='running'?(fr?'En cours':'Running'):(fr?'En attente':'Waiting')}</span></div><p className="expedition-place">{fr?'Salon public':'Public lobby'} · {fr?animal.themeFr:animal.themeEn}</p><h2 id={'expedition-'+r.id}>{r.name.fr}</h2><div className="expedition-meta"><span>{r.players} {fr?'joueur':'player'}{r.players>1?'s':''}</span><span>{r.language==='FR'?'FR · Français':'EN · English'}</span></div><Link className="expedition-join" href={'/lobby/'+r.id} aria-label={action+' — '+r.name.fr}>{action}<span aria-hidden="true">↗</span></Link></div><div className="expedition-art"><img src={'/assets/race-'+animal.landscape+'.png'} alt="" loading={index===0?'eager':'lazy'} width="1536" height="1024"/></div></article>}

export function Races(){const {state,c,fr}=useSite(),[races,setRaces]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[joinCode,setJoinCode]=useState(''),router=useRouter();
 async function refresh(showSpinner=false){if(showSpinner)setLoading(true);setError('');try{const data=await roomRequest(null);setRaces(data.rooms)}catch{setError(fr?'Impossible de charger les courses.':'Could not load races.')}finally{setLoading(false)}}
 useEffect(()=>{refresh(true);const timer=setInterval(()=>refresh(),8000);return()=>clearInterval(timer)},[fr]);
 const waiting=races.filter(r=>r.state==='waiting').length;
 return <main className="expeditions-page"><div className="expeditions-intro"><div><p className="expeditions-eyebrow">{fr?'SALONS PUBLICS':'PUBLIC LOBBIES'}</p><h1>{fr?'Parcourir les courses publiques':'Browse public races'}</h1><p className="expeditions-lead">{fr?'Choisis un salon en attente pour jouer, ou regarde une course déjà commencée.':'Choose a waiting lobby to play, or watch a race already underway.'}</p></div><div className="expeditions-intro-actions"><Link className="expedition-create" href="/private">{fr?'Créer une course':'Create a race'} <span aria-hidden="true">→</span></Link></div></div>
 <form className="course-code-entry" onSubmit={async e=>{e.preventDefault();setError('');try{const {id}=await roomRequest(null,{action:'resolve',code:joinCode});router.push('/lobby/'+id+'?code='+encodeURIComponent(joinCode.toUpperCase()))}catch(e){setError(e.message)}}}><label htmlFor="public-join-code">{fr?'J’ai un code':'I have a code'}</label><input id="public-join-code" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} maxLength={8} required placeholder={fr?'Code du salon':'Lobby code'}/><button className="wood-small-button">{fr?'Accéder au salon':'Open lobby'}</button></form>
 <div className="expeditions-toolbar"><span className="expeditions-scroll-hint">{!loading&&races.length?`${races.length} ${fr?'salon':'lobby'}${races.length>1?'s':''} · ${waiting} ${fr?'en attente':'waiting'}`:fr?'Les salons publics apparaissent ici':'Public lobbies appear here'}</span><div className="expeditions-tools"><details className="expeditions-identity"><summary><AnimalAvatar animal={state.avatar}/> {state.name} <span>⌄</span></summary><div className="expeditions-identity-panel"><Nickname/></div></details><button className="expeditions-refresh" onClick={()=>refresh(true)} disabled={loading} aria-label={c.refresh}>↻</button></div></div>
 {error&&<p role="alert" className="public-rooms-error">{error}</p>}{loading&&!races.length?<p role="status" className="public-rooms-loading">{c.loading}</p>:races.length?<section className="expedition-stack" aria-label={fr?'Courses publiques':'Public races'}>{races.map((r,index)=><RaceCard key={r.id} race={r} index={index} total={races.length}/>)}</section>:!error&&<div className="public-rooms-empty"><div className="public-rooms-empty-art" aria-hidden="true"/><div><p className="expeditions-eyebrow">{fr?'LA CLAIRIÈRE EST LIBRE':'THE CLEARING IS OPEN'}</p><h2>{fr?'Aucune course publique en attente':'No public race is waiting'}</h2><p>{fr?'Crée le premier salon, ou reviens voir les nouvelles courses bientôt.':'Create the first lobby, or check back for new races soon.'}</p><Link className="wood-primary" href="/private">{fr?'Créer une course':'Create a race'} <span aria-hidden="true">→</span></Link></div></div>}
 </main>}
