'use client';
import { useState } from 'react';
export default function RoomSettings({ settings: s, disabled, onChange }) { const [draft, setDraft] = useState(s); function change(key, value) { setDraft({ ...draft, [key]: value }); onChange({ [key]: value }); } const numeric = (key, label, min, max) => <div><label htmlFor={'setting-' + key}>{label}</label><input key={s[key]} id={'setting-' + key} type="number" min={min} max={max} defaultValue={s[key]} onBlur={e => { if (e.currentTarget.checkValidity() && Number(e.target.value) !== s[key])
    change(key, Number(e.target.value));
else
    e.target.value = String(s[key]); }} onKeyDown={e => { if (e.key === 'Enter')
    e.currentTarget.blur(); }}/></div>; return <fieldset className="room-settings-controls" disabled={disabled}><legend className="sr-only">Paramètres de course</legend><div className="wood-fields"><div><label htmlFor="setting-visibility">Visibilité</label><select id="setting-visibility" value={s.visibility} onChange={e => change('visibility', e.target.value)}><option value="public">Publique</option><option value="semi">Semi-publique</option><option value="private">Privée</option></select></div><div><label htmlFor="setting-text">Type de texte</label><select id="setting-text" value={s.textType} onChange={e => change('textType', e.target.value)}><option value="story">Phrases cohérentes</option><option value="words">Liste de mots</option><option value="custom">Texte personnalisé</option></select></div>{numeric('length', 'Longueur en mots', 20, 1000)}{numeric('timeLimit', 'Limite de temps (s) · 0 = sans limite', 0, 3600)}<div><label htmlFor="setting-errors">Gestion des erreurs</label><select id="setting-errors" value={s.blockErrors ? 'blocking' : 'free'} onChange={e => change('blockErrors', e.target.value === 'blocking')}><option value="free">Libre</option><option value="blocking">Bloquante</option></select></div><div><label htmlFor="setting-language">Langue du texte</label><select id="setting-language" value={s.language} onChange={e => change('language', e.target.value)}><option value="FR">Français</option><option value="EN">English</option></select></div></div><details className="wood-disclosure"><summary>Caractères et précision <span aria-hidden="true">+</span></summary><div className="wood-checks">{['punctuation', 'accents', 'numbers', 'specials'].map((key, i) => <label key={key}><input type="checkbox" checked={s[key]} onChange={e => change(key, e.target.checked)}/>{['Ponctuation', 'Accents', 'Chiffres', 'Caractères spéciaux'][i]}</label>)}</div><label htmlFor="setting-blacklist">Caractères à exclure</label><input key={s.blacklist} id="setting-blacklist" maxLength={100} defaultValue={s.blacklist} placeholder="Ex. : @{}" onBlur={e => { if (e.target.value !== s.blacklist)
    change('blacklist', e.target.value); }}/></details><details className="wood-disclosure" open={s.textType === 'custom' ? true : undefined}><summary>Texte et banques de mots <span aria-hidden="true">+</span></summary><label htmlFor="setting-bank">Thème de la banque de mots</label><select id="setting-bank" value={s.bank} onChange={e => change('bank', e.target.value)}><option value="jungle">Jungle</option><option value="adventure">Aventure</option><option value="science">Sciences</option></select><label htmlFor="setting-custom">Texte personnalisé</label><textarea key={s.customText} id="setting-custom" maxLength={15000} defaultValue={s.customText} placeholder="Colle ton texte ici, puis choisis « Texte personnalisé »." onBlur={e => { if (e.target.value !== s.customText)
    change('customText', e.target.value); }}/><p className="wood-hint">Les exclusions de caractères s’appliquent aussi à ce texte.</p></details><details className="wood-disclosure"><summary>Objectif et inactivité <span aria-hidden="true">+</span></summary><div className="wood-fields">{numeric('targetWpm', 'Objectif mots/min · 0 = aucun', 0, 400)}{numeric('inactiveAfter', 'Abandon après inactivité (s)', 15, 600)}</div><p className="wood-hint">L’objectif de vitesse est indicatif. Il ne bloque pas le départ.</p></details></fieldset>; }
