'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import type {RoomView} from '../../lib/room-types';
import {roomRequest} from '../../lib/room-client';
import {evolveAppearances,rankRacers,racerColour,speciesForRank,speciesLabels,type Appearance,type RunnerSpecies} from '../../lib/race-ranking';

import Runner from './Runner';
import Link from 'next/link';
import {useSite} from '../SiteContext';
export default function VisualRace({room,connected,onError}:{room:RoomView;connected:boolean;onError:(s:string)=>void}){
 const {save}=useSite();
 const me=room.people.find(p=>p.id===room.me)!,[value,setValue]=useState(me.input||''),[now,setNow]=useState(Date.now()),[appearances,setAppearances]=useState<Record<string,Appearance>>({});
 const activity=useRef<Record<string,{progress:number;at:number}>>({});
 const heatKey='guepard-heat-'+room.id+'-'+room.startedAt;
 const heat=useRef<Record<string,{hits:number;errors:number}>>({});
 useEffect(()=>{try{heat.current=JSON.parse(sessionStorage.getItem(heatKey)||'{}')}catch{}},[heatKey]);
 const latest=useRef(room),offset=useRef(room.serverNow-Date.now()),typed=useRef(me.typed||0),queued=useRef<string|null>(null),sending=useRef(false);latest.current=room;
 const finished=room.phase==='finished',countdown=Math.max(0,Math.ceil(((room.startedAt||0)-(now+offset.current))/1000)),elapsed=Math.max(0,(now+offset.current-(room.startedAt||0))/1000),ranks=rankRacers(room.people);
 useEffect(()=>{const timer=setInterval(()=>{setNow(Date.now());const r=latest.current;for(const p of r.people){const old=activity.current[p.id];if(!old||old.progress!==p.progress)activity.current[p.id]={progress:p.progress,at:Date.now()}}setAppearances(old=>evolveAppearances(r.people,old,Date.now(),r.phase==='finished'));if(queued.current!==null&&!sending.current&&r.phase==='running'){const next=queued.current;queued.current=null;sending.current=true;roomRequest(r.id,{action:'progress',value:next,typed:typed.current}).catch(e=>{onError(e.message);if(queued.current===null)queued.current=next}).finally(()=>{sending.current=false})}},180);return()=>clearInterval(timer)},[onError]);
 function type(next:string){if(next.length>value.length){for(let i=value.length;i<next.length;i++){const k=(room.text?.[i]||next[i]).toLowerCase(),entry=heat.current[k]||{hits:0,errors:0};entry.hits++;if(next[i]!==room.text?.[i])entry.errors++;heat.current[k]=entry}try{sessionStorage.setItem(heatKey,JSON.stringify(heat.current))}catch{}}if(next.length>value.length)typed.current+=next.length-value.length;if(room.settings.blockErrors&&!room.text!.startsWith(next))return;setValue(next);queued.current=next}
 const stateFor=(p:typeof me)=>p.abandoned?'Abandon':p.finishedAt?'Terminé':finished?'Temps écoulé':(p.id===room.me&&!connected)||(p.kind!=='bot'&&now+offset.current-p.seen>35000)?'Reconnexion…':'En course';
 function metrics(p:typeof me){const seconds=Math.max(1,((p.finishedAt||room.endedAt||room.serverNow)-(room.startedAt||0))/1000);return {speed:Math.round(p.progress/5/(seconds/60)),accuracy:Math.min(100,Math.round(p.progress/Math.max(1,p.typed)*100)),score:p.progress}}
 useEffect(()=>{if(!finished||me.role!=='player')return;const resultId=room.id+'-'+room.startedAt;const m=metrics(me);save('results',(old:any[])=>old.some(r=>r.id===resultId)?old:[...old,{id:resultId,date:room.endedAt||Date.now(),...m}])},[finished,room.id,room.startedAt,me.id]);
 const finalRank=ranks.filter(r=>!r.person.abandoned),podium=[finalRank[1],finalRank[0],finalRank[2]].filter(Boolean);
 return <div className="visual-race"><div className="visual-race-heading"><div><h2>{finished?'Le podium de la jungle':countdown?'Tout le monde sur la ligne de départ':'La course est lancée'}</h2><p>La piste indique la progression validée. L’animal représente le rang.</p></div><strong className="race-clock" role="status">{finished?'Course terminée':countdown?'Départ dans '+countdown:Math.floor(elapsed)+' s'}</strong></div>
 <p className="ranking-rule">{finished?'Classement final':'Classement en direct'} : ordre d’arrivée, puis progression ; abandons à la fin. Les égalités partagent le même rang. L’animal n’influence pas la frappe.</p>
 {finished&&<><div className="race-podium" aria-label="Podium"><div className="podium-confetti" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i} style={{left:(i*8)+'%',animationDelay:(i*.08)+'s'}}/>)}</div>{podium.map(({person:p,rank})=><div key={p.id} className={'podium-place podium-place-'+rank} style={{'--racer-colour':racerColour(p.id)} as CSSProperties}><Runner species={speciesForRank(rank,ranks.length)}/><strong>{p.name}{p.id===room.me?' · toi':''}</strong><span>{p.finishedAt?'Terminé':'Temps écoulé'}</span><div className="podium-plaque"><span>{metrics(p).speed} mots/min</span><span>{metrics(p).accuracy} % de précision</span><span>Score de frappe : {metrics(p).score}</span></div><div className="podium-step"><b>{rank}</b><span>{Math.round(p.progress/Math.max(1,room.text?.length||0)*100)} %</span></div></div>)}</div>{!podium.length&&<p className="wood-hint">La course s’est terminée sans joueur classé.</p>}<section className="your-result"><h3>Votre résultat</h3>{me.role==='spectator'?<p>Tu as suivi cette course comme spectateur.</p>:<p><strong>{metrics(me).speed} mots/min</strong> · {metrics(me).accuracy} % de précision · Score de frappe : {metrics(me).score}</p>}<small>Score de frappe = caractères validés. Le classement suit l’ordre d’arrivée, puis la progression.</small></section><details className="result-details" open><summary>Classement complet</summary><ol className="final-ranking">{ranks.map(({person:p,rank})=><li key={p.id}><b>{rank}.</b><Runner species={speciesForRank(rank,ranks.length)}/><strong>{p.name}</strong><span>{stateFor(p)}</span><span>{Math.round(p.progress/Math.max(1,p.typed)*100)} % de précision</span></li>)}</ol></details><details className="result-details"><summary>Statistiques individuelles et heatmap du clavier</summary><p>Les couleurs indiquent les erreurs sur les touches attendues pendant ta saisie sur cet appareil.</p>{Object.keys(heat.current).length?<div className="keyboard-heatmap">{[..."azertyuiopqsdfghjklmwxcvbn"].map(k=>{const h=heat.current[k];return <span key={k} style={{background:h?`rgba(242,140,40,${.15+.85*h.errors/h.hits})`:undefined}} title={h?`${h.hits} frappe(s), ${h.errors} erreur(s)`:'Non utilisée'}>{k.toUpperCase()}<small>{h?`${h.errors}/${h.hits}`:'—'}</small></span>})}</div>:<p>Aucune frappe enregistrée sur cet appareil pour cette course.</p>}<Link href="/stats">Mes statistiques →</Link></details></>}
 {!finished&&<><div className="race-lanes" aria-label="Pistes des participants">{room.people.filter(p=>p.role==='player').map(p=>{const result=ranks.find(r=>r.person.id===p.id)!,percent=Math.min(100,Math.max(0,p.progress/Math.max(1,room.text?.length||0)*100)),species=appearances[p.id]?.species||'cheetah';return <div key={p.id} className={'race-lane '+(p.id===room.me?'is-local ':'')+(p.abandoned?'is-abandoned':'')} data-player-id={p.id} style={{'--racer-colour':racerColour(p.id)} as CSSProperties}><div className="race-lane-label"><strong><i/>{p.name}{p.id===room.me?' · toi':''}</strong><span>#{result.rank}{result.tied?' ex æquo':''} · {speciesLabels[species]} · {Math.round(percent)} %</span><small>{countdown?'Au départ':stateFor(p)}</small></div><div className="race-lane-road" role="progressbar" aria-label={'Progression de '+p.name} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(percent)}><span className="lane-start">Départ</span><span className="lane-finish">Arrivée</span><div className="lane-travel"><div className="lane-position" style={{left:percent+'%'}}><Runner key={species} species={species} motion={countdown?'waiting':p.finishedAt?'arrived':p.abandoned||stateFor(p)==='Reconnexion…'?'stopped':p.progress>0&&now-(activity.current[p.id]?.at||0)<1400?'running':'stopped'}/></div></div></div></div>})}</div>
 {me.role==='spectator'?<p className="spectator-message" role="status">Mode spectateur. Tu suis les pistes et tu participeras à la prochaine course.</p>:<div className="race-typing"><div className="typing-title"><h3>À tes doigts de jouer</h3><span>{room.settings.blockErrors?'Correction obligatoire':'Erreurs libres'}</span></div><p className="target room-target">{[...room.text||''].map((ch,i)=><span key={i} className={i<value.length?ch===value[i]?'correct':'incorrect':''}>{ch}</span>)}</p><textarea aria-label="Texte de la course" value={value} onChange={e=>type(e.target.value.slice(0,room.text!.length))} disabled={countdown>0||me.abandoned||!!me.finishedAt||!connected} onPaste={e=>e.preventDefault()} onDrop={e=>e.preventDefault()} spellCheck={false} autoCapitalize="off" autoCorrect="off" placeholder="Tape le texte ici…"/>{!connected&&<p role="status">Reconnexion… Ta saisie est conservée.</p>}{me.finishedAt&&<p role="status">Terminé ! Tu peux suivre les autres pistes.</p>}{!me.abandoned&&!me.finishedAt&&<button className="woodland-back" onClick={()=>{queued.current=null;roomRequest(room.id,{action:'abandon'}).catch(e=>onError(e.message))}}>Abandonner la course</button>}</div>}</>}
 </div>
}
